### PR TITLE
Keyboard input interface

### PR DESCRIPTION
**Pull request by IkeRijsdijk**

### CODE REVIEW

**Comment by LiamClark** [comment]
The KeyBoardInputProcessor handles responsibilities for a lot of data classes in a very long update method, please break this down to responsibilities/ methods for the classes.

**Comment by IkeRijsdijk** [comment]
Looks good aside from the things Liam mentioned.

**Comment by MitchellHop** [comment]
I agree with the previous comments

**Comment by martinck** [comment]
Same opinion here

**Comment by LiamClark** [comment]
One problem with the colour class as en enum, with the next colour field as a mutable member in the enum instances, all players share the same next colour from one colour because all enum instances are singletons.

**Comment by MitchellHop** [comment]
:+1:

**Comment by Erackron** [comment]
:+1:

**Comment by martinck** [comment]
:+1:

**Pull request merged**
