### PR TITLE
player class tests

### PR DESCRIPTION
**Pull request by MitchellHop**

### CODE REVIEW

**Comment by LiamClark** [comment]
these tests provide some nice new coverage, but please consider #12.

**Comment by LiamClark** [comment]
The constructor for Player takes in a float argument for a double field, changing the argument would be a bit nicer since it removes an implicit promotion of the variable

**Comment by IkeRijsdijk** [comment]
Couldn't find any problems with this code, seems ready to merge

**Comment by martinck** [comment]
Nice refactor to shorten the test code properly.

**Pull request merged**
